### ISSUE TITLE
middleware Webman\Log\Middleware::process not exsits

### ISSUE THREAD

**Issue by Colin9R** [webman-php/log#11]
会报这个错误 middleware Webman\Log\Middleware::process not exsits

然后我把config/plugin/webman/log/middleware.php 这个文件改成大写Middleware.php就好了,是啥原因？

**Comment by walkor** [comment]
一般是composer require完后没restart重启webman导致的

**Comment by zkamisama** [comment]
![image](https://github.com/user-attachments/assets/1cea1999-36a1-4787-9cbe-112fdccb5192)

我也有这个问题， 已经restart了， 还是会报错
