### ISSUE TITLE
关于使用 middleware 的疑问

### ISSUE THREAD

**Issue by krissss** [webman-php/log#3]
middleware 每次 request 都会加载，但是像 laravel 的 Db::listen 是持久化的，那会导致一直追加 listen
目前没有导致 log 一直增加的原因是 $this->log 是每次都是重新赋值为空的
是否有其他解决方案解决这个问题，比如使用 bootstrap ？

**Comment by walkor** [comment]
```
function ()
{
    static $initialized;
    if (!$initialized) {
        Db::listen(...);
        $initialized = true;
    }
}
```
这个代码结构会保证当前进程内Db::listen不会重复监听

**Comment by krissss** [comment]
ok，谢谢
