### ISSUE TITLE
log里打印异常，是不是和框架的重复了

### ISSUE THREAD

**Issue by as5739** [webman-php/log#4]
```php
        if (method_exists($response, 'exception') && $exception = $response->exception()) {
            $logs .= $exception;
            Log::error($logs);
        } else {
            Log::info($logs);
        }
```
这段，框架的Handler也会打印log，这边又重新打印了一遍，重复了。还有例如抛出自定义验证错误的异常ValidateException，框架Handler里可以在$dontReport里不输出，但这里就没法设置了。

**Comment by walkor** [comment]
框架的Exception Handler和这个webman/log插件是独立的，互不影响，框架的Exception Handler也不应该受到一个插件的影响。
webman/log 没有区分异常，只要是异常就全部记录，如果你需要webman/log不记录某些异常，可以发pr，把排除的异常配置到config/plugin/webman/log/app.php 中，上面代码判断下。
