### ISSUE TITLE
tp-orm的sql日志不记录

### ISSUE THREAD

**Issue by yuanzhihai** [webman-php/log#7]
tp-orm的sql日志不记录
laravel-orm 没问题

**Comment by yuanzhihai** [comment]
日志中间件
$sql_logs = ThinkDb::getDbLog(true);
取到是空

在控制器可以取到

**Comment by walkor** [comment]
确保你用的是最新的log插件。
尝试将config/plugin/webman/log/middleware.php 里 `Webman\Log\Middleware::class` 移动到 `config/middleware.php` 里，放在最前面。

**Comment by yuanzhihai** [comment]
> 确保你用的是最新的log插件。 尝试将config/plugin/webman/log/middleware.php 里 `Webman\Log\Middleware::class` 移动到 `config/middleware.php` 里，放在最前面。

使用的最新版
中间件放最前面也一样，
调试 $sql_logs = ThinkDb::getDbLog(true); 中间件里取不到值

**Comment by yuanzhihai** [comment]
think-orm  版本 v2.0.59

**Comment by walkor** [comment]
不要在其它地方调用ThinkDb::getDbLog，调用后可能会删除sql日志，中间件就拿不到了

**Comment by yuanzhihai** [comment]
> 不要在其它地方调用ThinkDb::getDbLog，调用后可能会删除sql日志，中间件就拿不到了

没有在其他地方调用

**Comment by yuanzhihai** [comment]
反正就是不记录

**Comment by yuanzhihai** [comment]
找到原因了，arms 这个插件里 取走了
